/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication21;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author 1075474
 */
public class PedraPapelTesoura extends javax.swing.JFrame {

    /**
     * Creates new form PedraPapelTesoura
     */
    public PedraPapelTesoura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoescolhas = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPTtitle = new javax.swing.JPanel();
        jPBody = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPedra = new javax.swing.JRadioButton();
        jPapel = new javax.swing.JRadioButton();
        jTesoura = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlresult = new javax.swing.JLabel();
        jStart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        juserchoicee = new javax.swing.JLabel();
        jbotchoicee = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPBody.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Selecione sua jogada: ");

        grupoescolhas.add(jPedra);
        jPedra.setText("Pedra");

        grupoescolhas.add(jPapel);
        jPapel.setText("Papel");

        grupoescolhas.add(jTesoura);
        jTesoura.setText("Tesoura");

        jLabel3.setText("User:");

        jlresult.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jStart.setText("Jogar");
        jStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jlresult, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jStart)
                        .addGap(176, 176, 176))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jlresult, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jLabel4.setText("Bot:");

        juserchoicee.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        juserchoicee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        juserchoicee.setText(" ");

        jbotchoicee.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jbotchoicee.setText(" ");

        javax.swing.GroupLayout jPBodyLayout = new javax.swing.GroupLayout(jPBody);
        jPBody.setLayout(jPBodyLayout);
        jPBodyLayout.setHorizontalGroup(
            jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBodyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jPedra))
                .addGroup(jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPapel)
                        .addGap(100, 100, 100)
                        .addComponent(jTesoura)
                        .addGap(29, 29, 29))
                    .addGroup(jPBodyLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPBodyLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(juserchoicee, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jbotchoicee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
            .addGroup(jPBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBodyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(125, 125, 125))
        );
        jPBodyLayout.setVerticalGroup(
            jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPedra)
                    .addComponent(jPapel)
                    .addComponent(jTesoura))
                .addGap(51, 51, 51)
                .addGroup(jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juserchoicee)
                    .addComponent(jbotchoicee))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );

        javax.swing.GroupLayout jPTtitleLayout = new javax.swing.GroupLayout(jPTtitle);
        jPTtitle.setLayout(jPTtitleLayout);
        jPTtitleLayout.setHorizontalGroup(
            jPTtitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTtitleLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jPBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPTtitleLayout.setVerticalGroup(
            jPTtitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTtitleLayout.createSequentialGroup()
                .addComponent(jPBody, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Pedra, Papel, Tesoura!!!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jPTtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPTtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartActionPerformed
        String userchoice = "";
        
        if (jPapel.isSelected()){
            juserchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/papelp.png")));
            userchoice = "papel";
        }
        
        if (jPedra.isSelected()){
            juserchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/pedra.png")));
            userchoice = "pedra";
        }
        if (jTesoura.isSelected()){
            juserchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/tesoura.png")));
            userchoice = "tesoura";
        }
        
        if (userchoice.equals("")){
            JOptionPane.showMessageDialog(null, "Você precisa escolher uma opção!\nVamos tentar novamente!");
        } else {
            start(userchoice);
        }
    }//GEN-LAST:event_jStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedraPapelTesoura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedraPapelTesoura().setVisible(true);
            }
        });
    }

    public void start(String escolhaUser){
        calculaVencedor(escolhaUser, escolhaBOT());
    }
    
    public static String escolhaBOT(){
        Random rd = new Random();
        int valorSorteado = rd.nextInt(3);
        
        if (valorSorteado == 0){
            return "pedra";
        }
        
        if (valorSorteado == 1){
            return "papel";
        }
        
        if (valorSorteado == 2){
            return "tesoura";
        }
        
        return null;
    }
    
    public void calculaVencedor(String user, String bot){
        
        if(user.equals("pedra") && bot.equals("tesoura")){ 
            jbotchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/tesoura.png")));
            jlresult.setText("O usuário ganhou!");
        } else if (user.equals("papel") && bot.equals("pedra")){
            jbotchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/pedra.png")));
            jlresult.setText("O usuário ganhou!");
        } else if (user.equals("tesoura") && bot.equals("papel")){
            jbotchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/papelp.png")));
            jlresult.setText("O usuário ganhou!");
        } else if(user.equals(bot)){
            if (user.equals("pedra")){
                jbotchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/pedra.png")));
            } else if (user.equals("papel")) {
                jbotchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/papelp.png")));
            } else {
                jbotchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/tesoura.png")));
            }
            
            jlresult.setText("Temos um empate!");
        } else {
            if (bot.equals("pedra")){
                jbotchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/pedra.png")));
            } else if (bot.equals("papel")) {
                jbotchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/papelp.png")));
            } else {
                jbotchoicee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgPPT/tesoura.png")));
            }
            jlresult.setText("O bot ganhou!");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoescolhas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPBody;
    private javax.swing.JPanel jPTtitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jPapel;
    private javax.swing.JRadioButton jPedra;
    private javax.swing.JButton jStart;
    private javax.swing.JRadioButton jTesoura;
    private javax.swing.JLabel jbotchoicee;
    private javax.swing.JLabel jlresult;
    private javax.swing.JLabel juserchoicee;
    // End of variables declaration//GEN-END:variables
}
